name: wifi_info_enhanced
description: Flutter plugin for getting WiFi information with improved iOS and Android support
version: 1.1.0
homepage: https://github.com/alxmoroz/flutter_wifi_info_enhanced

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: team.moroz.wifi_info_enhanced
        pluginClass: WifiInfoEnhancedPlugin
      ios:
        pluginClass: WifiInfoEnhancedPlugin
